# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest  # 选择 macOS 环境来构建

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 克隆代码

      - name: Set up CocoaPods
        run: |
          sudo gem install cocoapods  # 安装 CocoaPods

      - name: Install CocoaPods dependencies
        run: |
          pod install  # 安装 CocoaPods 依赖

      - name: Build the project
        run: |
          xcodebuild clean build \
            -workspace uPic.xcworkspace \
            -scheme uPic \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Archive the project
        run: |
          xcodebuild -workspace uPic.xcworkspace -scheme uPic -configuration Release archive -archivePath $PWD/build/uPic.xcarchive  # 构建归档
